[package]
name = "yakui-sdl3"
description = "sdl3 bindings for yakui"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SecondHalfGames/yakui"
edition = "2021"

[dependencies]
yakui-core = { path = "../yakui-core", version = "0.3.0" }

sdl3.workspace = true
