[package]
name = "yakui"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "crates/*"]
default-members = [".", "crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.21.2"
mopa = "0.2.2"
thunderdome = "0.5.0"
