[package]
name = "yakui"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "crates/*"]
default-members = [".", "crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.10.0", features = ["derive"] }
glam = { version = "0.21.2", features = ["bytemuck"] }
thunderdome = "0.5.0"
