[package]
name = "yakui-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
bitflags = "1.3.2"
glam = "0.21.2"
log = "0.4.17"
palette = "0.6.0"
thunderdome = "0.5.1"
