[package]
name = "yakui-widgets"
description = "Built-in widgets for yakui"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LPGhatguy/yakui"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yakui-core = { path = "../yakui-core", version = "0.1.0" }

fontdue = "0.7.2"

[dev-dependencies]
yakui = { path = "../yakui" }
yakui-test = { path = "../yakui-test" }

insta = "1.15.0"
