[package]
name = "yakui-widgets"
description = "Built-in widgets for yakui"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LPGhatguy/yakui"
edition = "2021"

[features]
default = ["default-fonts"]

# Include built-in fonts.
default-fonts = []

[dependencies]
yakui-core = { path = "../yakui-core", version = "0.1.0" }

fontdue = "0.7.2"
thunderdome = "0.5.1"
smol_str = "0.1.23"

[dev-dependencies]
yakui = { path = "../yakui" }
yakui-test = { path = "../yakui-test" }

insta = "1.15.0"
