[package]
name = "yakui-wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yakui = { path = "../.." }

wgpu = "0.13.1"
glam = { version = "0.21.2", features = ["bytemuck"] }
bytemuck = { version = "1.10.0", features = ["derive"] }
